/*
###
###
###
###
###
###
###
###
###
###
###
###       PLEASE DO NOT EDIT THIS FILE
###       FOR DevMastery TESTING PURPOSES!
###
###       THIS FILE IS FOR DevMastery TO BE ABLE TO TEST YOUR CODE PROPERLY
###       CHANGING THIS FILE CAN BREAK THE PROCESS OF VERIFICATION

██████╗░███████╗██╗░░░██╗███╗░░░███╗░█████╗░░██████╗████████╗███████╗██████╗░██╗░░░██╗
██╔══██╗██╔════╝██║░░░██║████╗░████║██╔══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗╚██╗░██╔╝
██║░░██║█████╗░░╚██╗░██╔╝██╔████╔██║███████║╚█████╗░░░░██║░░░█████╗░░██████╔╝░╚████╔╝░
██║░░██║██╔══╝░░░╚████╔╝░██║╚██╔╝██║██╔══██║░╚═══██╗░░░██║░░░██╔══╝░░██╔══██╗░░╚██╔╝░░
██████╔╝███████╗░░╚██╔╝░░██║░╚═╝░██║██║░░██║██████╔╝░░░██║░░░███████╗██║░░██║░░░██║░░░
╚═════╝░╚══════╝░░░╚═╝░░░╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝░░░╚═╝░░░

###
###
###
###
###
###
###
###
###
###
*/


// Runtime storage of whether the user has completed certain challenges or not.

//These get sent with the response when DevMastery hits the test-endpoint for each corresponding challenge.

exports.userPassedConsoleChallenge = false;
exports.userPassedLoggerChallenge = false;
exports.bodyParserMountPosition = 0;
exports.cookieParserMountPosition = 0;
exports.nowRouteStackLength = 0;